version: '3.9'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: springdb
      MYSQL_ROOT_PASSWORD: secret


  app:
    build: .
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/springdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
      spring.datasource.username: root
      spring.datasource.password: secret